In [27]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\nabee\anaconda3\lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (7.34.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: keras>=3.12.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (2.0.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\nabee\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nabee\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\nabee\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Requirement already satisfied: namex in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\nabee\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\nabee\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\nabee\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\nabee\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [28]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [29]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [30]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [31]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [32]:
X= df[['soil_moisture','temperature_c', 'sunlight_hours']]
Y = df['needs_water']

In [33]:
X_min = X.min()
X_max = X.max()
X_scaled = (X-X_min)/( X_max- X_min + 1e-8)

In [34]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, Y, test_size=0.25, random_state=42)

In [36]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [37]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=2,verbose=1
)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5833 - loss: 0.6374 - val_accuracy: 0.2500 - val_loss: 0.6811
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6363 - val_accuracy: 0.2500 - val_loss: 0.6802
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5833 - loss: 0.6355 - val_accuracy: 0.2500 - val_loss: 0.6793
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5833 - loss: 0.6343 - val_accuracy: 0.2500 - val_loss: 0.6784
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5833 - loss: 0.6342 - val_accuracy: 0.2500 - val_loss: 0.6776
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6325 - val_accuracy: 0.2500 - val_loss: 0.6767
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6313 - val_accuracy: 0.2500 - val_loss: 0.6758
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6307 - val_accuracy: 0.2500 - val_loss: 0.6749
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6297 - val_accuracy: 0.2500 - val_loss: 0.6740
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6298 - val_accuracy: 0.2500 - val_loss: 0.6731
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6285 - val_accuracy: 0.2500 - val_loss: 0.6723
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6270 - val_accuracy: 0.2500 - val_loss: 0.6714
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5833 - loss: 0.6260 - val_accuracy: 0.2500 - val_loss: 0.6705
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6260 - val_accuracy: 0.2500 - val_loss: 0.6696
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5833 - loss: 0.6252 - val_accuracy: 0.2500 - val_loss: 0.6687
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6243 - val_accuracy: 0.2500 - val_loss: 0.6679
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5833 - loss: 0.6228 - val_accuracy: 0.2500 - val_loss: 0.6670
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6227 - val_accuracy: 0.2500 - val_loss: 0.6661
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5833 - loss: 0.6229 - val_accuracy: 0.2500 - val_loss: 0.6652
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6213 - val_accuracy: 0.2500 - val_loss: 0.6643
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6203 - val_accuracy: 0.2500 - val_loss: 0.6635
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6197 - val_accuracy: 0.2500 - val_loss: 0.6626
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5833 - loss: 0.6183 - val_accuracy: 0.2500 - val_loss: 0.6617
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5833 - loss: 0.6195 - val_accuracy: 0.2500 - val_loss: 0.6609
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6171 - val_accuracy: 0.2500 - val_loss: 0.6601
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5833 - loss: 0.6171 - val_accuracy: 0.2500 - val_loss: 0.6593
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6151 - val_accuracy: 0.2500 - val_loss: 0.6584
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.5833 - loss: 0.6159 - val_accuracy: 0.2500 - val_loss: 0.6575
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5833 - loss: 0.6134 - val_accuracy: 0.2500 - val_loss: 0.6566
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6135 - val_accuracy: 0.2500 - val_loss: 0.6558
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6125 - val_accuracy: 0.2500 - val_loss: 0.6549
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6110 - val_accuracy: 0.2500 - val_loss: 0.6541
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5833 - loss: 0.6116 - val_accuracy: 0.2500 - val_loss: 0.6532
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.6667 - loss: 0.6094 - val_accuracy: 0.2500 - val_loss: 0.6523
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6089 - val_accuracy: 0.2500 - val_loss: 0.6515
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6080 - val_accuracy: 0.2500 - val_loss: 0.6506
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6081 - val_accuracy: 0.2500 - val_loss: 0.6497
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.6074 - val_accuracy: 0.2500 - val_loss: 0.6489
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.6061 - val_accuracy: 0.2500 - val_loss: 0.6480
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6059 - val_accuracy: 0.2500 - val_loss: 0.6471
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6053 - val_accuracy: 0.2500 - val_loss: 0.6462
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6061 - val_accuracy: 0.2500 - val_loss: 0.6453
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6036 - val_accuracy: 0.2500 - val_loss: 0.6445
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6035 - val_accuracy: 0.2500 - val_loss: 0.6437
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6030 - val_accuracy: 0.2500 - val_loss: 0.6429
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6020 - val_accuracy: 0.2500 - val_loss: 0.6420
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6016 - val_accuracy: 0.2500 - val_loss: 0.6412
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6008 - val_accuracy: 0.2500 - val_loss: 0.6404
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5992 - val_accuracy: 0.2500 - val_loss: 0.6395
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5986 - val_accuracy: 0.2500 - val_loss: 0.6387
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5979 - val_accuracy: 0.2500 - val_loss: 0.6379
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.5981 - val_accuracy: 0.2500 - val_loss: 0.6371
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5974 - val_accuracy: 0.2500 - val_loss: 0.6362
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5967 - val_accuracy: 0.2500 - val_loss: 0.6353
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5974 - val_accuracy: 0.2500 - val_loss: 0.6344
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5951 - val_accuracy: 0.2500 - val_loss: 0.6335
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5939 - val_accuracy: 0.2500 - val_loss: 0.6327
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.5951 - val_accuracy: 0.2500 - val_loss: 0.6318
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5935 - val_accuracy: 0.2500 - val_loss: 0.6310
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5929 - val_accuracy: 0.2500 - val_loss: 0.6302
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5925 - val_accuracy: 0.5000 - val_loss: 0.6294
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5917 - val_accuracy: 0.5000 - val_loss: 0.6286
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5903 - val_accuracy: 0.5000 - val_loss: 0.6278
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5896 - val_accuracy: 0.5000 - val_loss: 0.6269
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5888 - val_accuracy: 0.5000 - val_loss: 0.6261
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5891 - val_accuracy: 0.5000 - val_loss: 0.6252
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5875 - val_accuracy: 0.5000 - val_loss: 0.6244
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5869 - val_accuracy: 0.5000 - val_loss: 0.6235
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5870 - val_accuracy: 0.5000 - val_loss: 0.6227
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5858 - val_accuracy: 0.5000 - val_loss: 0.6218
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.5873 - val_accuracy: 0.5000 - val_loss: 0.6210
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5842 - val_accuracy: 0.5000 - val_loss: 0.6201
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5850 - val_accuracy: 0.5000 - val_loss: 0.6193
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.5839 - val_accuracy: 0.5000 - val_loss: 0.6185
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5822 - val_accuracy: 0.5000 - val_loss: 0.6177
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5825 - val_accuracy: 0.5000 - val_loss: 0.6167
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5809 - val_accuracy: 0.5000 - val_loss: 0.6159
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5811 - val_accuracy: 0.5000 - val_loss: 0.6150
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5795 - val_accuracy: 0.5000 - val_loss: 0.6142
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5803 - val_accuracy: 0.5000 - val_loss: 0.6133
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.5795 - val_accuracy: 0.5000 - val_loss: 0.6126
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.5776 - val_accuracy: 0.5000 - val_loss: 0.6118
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.6667 - loss: 0.5768 - val_accuracy: 0.5000 - val_loss: 0.6109
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5778 - val_accuracy: 0.5000 - val_loss: 0.6101
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5754 - val_accuracy: 0.5000 - val_loss: 0.6092
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5752 - val_accuracy: 0.5000 - val_loss: 0.6084
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5741 - val_accuracy: 0.5000 - val_loss: 0.6075
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5757 - val_accuracy: 0.5000 - val_loss: 0.6067
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5736 - val_accuracy: 0.5000 - val_loss: 0.6058
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5721 - val_accuracy: 0.5000 - val_loss: 0.6049
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5712 - val_accuracy: 0.7500 - val_loss: 0.6041
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5712 - val_accuracy: 0.7500 - val_loss: 0.6032
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6667 - loss: 0.5704 - val_accuracy: 0.7500 - val_loss: 0.6023
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.5698 - val_accuracy: 0.7500 - val_loss: 0.6014
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5686 - val_accuracy: 0.7500 - val_loss: 0.6006
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.6667 - loss: 0.5685 - val_accuracy: 0.7500 - val_loss: 0.5997
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5669 - val_accuracy: 0.7500 - val_loss: 0.5994
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.5666 - val_accuracy: 0.7500 - val_loss: 0.5990
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.5662 - val_accuracy: 0.7500 - val_loss: 0.5986
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.6667 - loss: 0.5657 - val_accuracy: 0.7500 - val_loss: 0.5982

In [39]:
from tensorflow.keras import optimizers

In [40]:
opt = optimizers.SGD(learning_rate = 0.01, momentum = 0.9)